version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8585:8585"
    image: ayaissa/backend-maintenance:v1
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    image: ayaissa/frontend-maintenance:v1
    restart: unless-stopped

  jenkins:
    build: ./jenkins
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

volumes:
  jenkins_home:
